name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Stop server
        run: pm2 stop hubs_admin_server

      - name: Install hubs deps
        run: npm ci --force

      - name: Build for Hubs
        run: npm run build

      - name: Install hubs admin deps
        run: |
          cd admin/
          pwd
          npm ci --force
          ls

      - name: Start server
        run: pm2 start hubs_admin_server
